# Generated by Django 3.1.7 on 2022-03-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser',
            name='pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
