# Generated by Django 3.1.7 on 2022-04-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_dispenser_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
    ]
